name = "cloud-clipboard"
type = "python"
account_id = "19e149e307f00d51d876002ea98ae316"
workers_dev = true

[site]
bucket = "./public"
entry-point = "workers"

[build]
command = "pip install -r requirements.txt && python app.py"
[build.upload]
format = "modules"